server:
  port: 8091
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: YOUR_HOST
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: YOUR_URL
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 1
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  flyway:
    baseline-description:
    baseline-version: 20231209001
    baseline-on-migrate: true
    default-schema: mysql-homework
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jz.cbq.backend.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
      table-prefix: t_
logging:
  level:
    jz:
      cbq:
        backend:
          mapper: INFO
cbq:
  admin-secret: TODO
  jwt-secret: TODO